### ISSUE TITLE
An example with actual data and time, please 

### ISSUE THREAD

**Issue by PhoebeRainbow** [kentang2017/kinqimen#1]
Dear author!

Thank you for your work and sharing on this Qimen library?

Can you please give an example?

I've tried below but both of them gave erros:

    kinqimen.Qimen(2021, 3, 5, 11).pan()
    # TypeError: 'NoneType' object is not subscriptable

    kinqimen.Qimen("2021", "3", "5", "11:00").pan()
    # TypeError: in method 'Lunar_getDayBySolar', argument 2 of type 'int'

Thanks again.

**Comment by kentang2017** [comment]
the error is fixed. it comes from the current jieqi 驚蟄 instead of 驚蛰

**Comment by PhoebeRainbow** [comment]
Good morning @kentang2017,

Thank you for the update of the “config.py”! 

It works very well now (with given integers for the year, month, day and time)

    kinqimen.Qimen(2021, 3, 5, 11).pan(), 

Can you please update the package so that users download and use PIP install can enjoy this update?

Thanks again.!
