### ISSUE TITLE
`ImportError: cannot import name 'Qimen'

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#10]
Hi Mr. Tang,

Hope you are very well! :)

When I tried: 
`from kinqimen import Qimen`

It gives:

`ImportError: cannot import name 'Qimen' from 'kinqimen' (C:\Python38\lib\site-packages\kinqimen\__init__.py)`

Can you please have a look? Thank you.

**Comment by kentang2017** [comment]
from kinqimen import kinqimen

**Comment by P-Rainbow** [comment]
Thank you!

Would you consider to upgrade the example on 

`https://github.com/kentang2017/kinqimen`
`3. 起課方式 Quickstart`
