### ISSUE TITLE
Dates in June, TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#11]
Hi Mr. Tang,

An error pops when date and time "2021,6,21,15" is used. (no error if it changed to May or July) 

Can you please have a look? Thank you!

`from kinqimen import kinqimen`
`qimen = kinqimen.Qimen(2021,6,21,15).pan()`
`print (qimen)`

It gives error:

`Traceback (most recent call last):
  File "C:\My Documents\Scripts\good.py", line 5, in <module>
    qimen = kinqimen.Qimen(2021,6,21,15).pan()
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 18, in __init__
    self.g = self.gpan()
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 212, in gpan
    gong = dict(zip(start_jia, start_gong)).get(shun)
TypeError: 'NoneType' object is not iterable`

**Comment by kentang2017** [comment]
fixed, please upgrade

**Comment by P-Rainbow** [comment]
Thank you for the update.

But when using kinqimen 0.0.4.2, it gives:
`from config import *
ModuleNotFoundError: No module named 'config'`

**Comment by kentang2017** [comment]
fixed and please try again

**Comment by P-Rainbow** [comment]
Bravo, @kentang2017. Great work!

Stay safe and take care!
