### ISSUE TITLE
Adding 馬星 and 旬空

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#2]
Thanks author Mr. Tang's effort and sharing of such a good tool!

Is it possible to add on below information:
1. 馬星
2. 旬空（年月日時 空）

Thanks again!

**Comment by kentang2017** [comment]
> Thanks author Mr. Tang's effort and sharing of such a good tool!
> 
> Is it possible to add on below information:
> 
> 1. 馬星
> 2. 旬空（年月日時 空）
> 
> Thanks again!

will add up soon, thank you for your appreciation!

**Comment by P-Rainbow** [comment]
@kentang2017, thanks!

This library is the only one Qimen Python library and stands as a good pioneer. Great job!

Can we keep this question open until the update is ready? Much looking forward to see it.

**Comment by kentang2017** [comment]
> @kentang2017, thanks!
> 
> This library is the only one Qimen Python library and stands as a good pioneer. Great job!
> 
> Can we keep this question open until the update is ready? Much looking forward to see it.

yes for sure :)

**Comment by kentang2017** [comment]
actually i have included the function 日空時空 already.
you can try self.daykong_shikong()

**Comment by P-Rainbow** [comment]
@kentang2017 Mr. Tang, can you please by the way teach me how to use the "self"?

I tried:
    qimen = kinqimen.Qimen(2021, 3, 8, 10).pan()
    print (qimen.daykong_shikong())

It rives error:
    AttributeError: 'dict' object has no attribute 'daykong_shikong'

**Comment by P-Rainbow** [comment]
@kentang2017, superb! thank you for fixing the issue! :)

**Comment by kentang2017** [comment]
馬星 is added

**Comment by P-Rainbow** [comment]
@kentang2017 marvelous and great job!
