### ISSUE TITLE
TypeError: zip argument #2 must support iteration

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#21]
Good morning Mr. Tang!

An error pops when using Kinqimen 0.0.4.6 (with sxtwl 2.0.4) for 2021 July 05th 18:00.

Can you please have a look?

Thank you!

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    [<ipython-input-6-020c97746880>](https://localhost:8080/#) in <module>()
      1 from kinqimen import kinqimen
      2 
    ----> 3 qimen = kinqimen.Qimen(2021,7,5,18).pan()
      4 
      5 print (qimen)

    1 frames
    [/usr/local/lib/python3.7/dist-packages/kinqimen/kinqimen.py](https://localhost:8080/#) in gpan(self)
    246         start_gong = start_gong_d.get(multi_key_dict_get({tuple(jieqi_all[0:12]):"冬至", tuple(jieqi_all[13:24]):"夏至"}, self.find_jieqi()))
    247         yy = yy_dun.get(multi_key_dict_get({tuple(jieqi_all[0:12]):"冬至", tuple(jieqi_all[13:24]):"夏至"}, self.find_jieqi()))
    --> 248         gong = dict(zip(start_jia, start_gong)).get(shun)
    249         triple_list = list(map(lambda x: x + x + x, list(range(0,21))))
    250         b = []

    TypeError: zip argument #2 must support iteration

**Comment by kentang2017** [comment]
fixed & try again pls

**Comment by P-Rainbow** [comment]
@kentang2017 , Superb, Mr. Tang!

Thanks for the fix. You're brilliant!
