### ISSUE TITLE
ValueError: None is not in list, for (2022,2,9,23)

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#22]
Dear Mr. Tang,

Sorry to trouble you again.

It pops ValueError: None is not in list, when using kinqimen for (2022,2,9,23).

Can you please have a look? Thank you!

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    [<ipython-input-4-8de370ffa6bb>](https://localhost:8080/#) in <module>()
      1 from kinqimen import kinqimen
      2 
    ----> 3 qimen = kinqimen.Qimen(2022,2,9,23).pan()
      4 
      5 print (qimen)

    2 frames
    [/usr/local/lib/python3.7/dist-packages/kinqimen/config.py](https://localhost:8080/#) in new_list(olist, o)
     24 
     25 def new_list(olist, o):
    ---> 26     zhihead_code = olist.index(o)
     27     res1 = []
     28     for i in range(len(olist)):

    ValueError: None is not in list

**Comment by kentang2017** [comment]
fixed & pls try again.

But there is a minor issue on sxtwl that daygangzhi of  2022,2,9,23 is 癸巳 but not 甲午.

**Comment by P-Rainbow** [comment]
@kentang2017 , thanks again for the update and the note, dear Mr. Tang! It works now!
