### ISSUE TITLE
Allocation of '神', version 0.0.5.0

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#25]
Hi Mr. Tang,

By using kinqimen 0.0.5.0, for 2005年01月19日23时, it gives '神': {'艮': '符', '震': '蛇'...

But it seems '蛇' should be at '兑'.

Can you please have a look? Thank you.

**Comment by kentang2017** [comment]
fixed. the problem comes from jieqi setting

**Comment by P-Rainbow** [comment]
Thank you Mr. Tang @kentang2017 for the fix!

But with version 0.0.5.2, it still gives me the same.

**Comment by kentang2017** [comment]
pls try 0.0.5.4

**Comment by P-Rainbow** [comment]
Thank you for the update.

Seems we're almost there! :)

    Traceback (most recent call last):
      File "C:\My Documents\Qimen 1.py", line 1, in <module>
        from kinqimen import kinqimen
      File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 6, in <module>
        from config import *
    **ModuleNotFoundError: No module named 'config'**

**Comment by kentang2017** [comment]
pls update to 0.0.5.5

**Comment by P-Rainbow** [comment]
Thanks for the update, @kentang2017 Mr. Tang.

But I am sorry to tell, by using kinqimen 0.0.5.5, for 2005年01月19日23时, it still gives '神': {'艮': '符', '震': '蛇'..., which shall be  should be at ...'兑':'蛇'...

**Comment by kentang2017** [comment]
Did you uninstall and install again?

**Comment by kentang2017** [comment]
my output is:
{'干支': '甲申年丁丑月甲辰日甲子時', '旬首': '壬', '旬空': {'日空': '寅卯', '時空': '戌亥'}, '局日': '甲己日', '排局': '陽遁五局下元', '節氣': '小寒', '值符值使': {'值符星宮': ['禽', '中'], '值使門宮': ['死', '中']}, '天乙': '禽', '天盤': [{'中': '戊', '乾': '己', '兌': '庚', '艮': '辛', '離': '壬', '坎': '癸', '坤': '丁', '震': '丙', '巽': '乙'}, {'戊': '中', '己': '乾', '庚': '兌', '辛': '艮', '壬': '離', '癸': '坎', '丁': '坤', '丙': '震', '乙': '巽'}, ['癸', '辛', '丙', '乙', '壬', '丁', '庚', '己']], '地盤': {'中': '戊', '乾': '己', '兌': '庚', '艮': '辛', '離': '壬', '坎': '癸', '坤': '丁', '震': '丙', '巽': '乙'}, '門': {'坤': '死', '兌': '驚', '乾': '開', '坎': '休', '艮': '生', '震': '傷', '巽': '杜', '離': '景'}, '星': {'坤': '禽', '兌': '柱', '乾': '心', '坎': '蓬', '艮': '任', '震': '沖', '巽': '輔', '離': '英'}, '神': {'坤': '符', '兌': '蛇', '乾': '陰', '坎': '合', '艮': '勾', '震': '雀', '巽': '地', '離': '天'}, '馬星': {'天馬': '戌', '丁馬': '未', '驛馬': '寅'}, '長生運': {'天盤': {'中': {'戊': '養'}, '乾': {'己': '墓'}, '兌': {'庚': '絕'}, '艮': {'辛': '胎'}, '離': {'壬': '長生'}, '坎': {'癸': '沐浴'}, '坤': {'丁': '死'}, '震': {'丙': '病'}}, '地盤': {'中': {'戊': '養'}, '乾': {'己': '墓'}, '兌': {'庚': '絕'}, '艮': {'辛': '胎'}, '離': {'壬': '長生'}, '坎': {'癸': '沐浴'}, '坤': {'丁': '死'}, '震': {'丙': '病'}, '巽': {'乙': '帝旺'}}}}

**Comment by kentang2017** [comment]
because of the 干支 setting. 

depending on you consider 

2005年01月19日23时  as 癸卯日甲子時 
or 
甲辰日甲子時

suggest you set 23:00 as another day's 子時

**Comment by kentang2017** [comment]
try 0.0.5.6, i already set 23:00 as the other day's 子時

**Comment by P-Rainbow** [comment]
Thank you @kentang2017 Mr. Tang for the hard work (and sorry for the late reply).

0.0.5.6 perfectly solved the problem! :)
