### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#3]
Great to see the latest update on 09th March 2021!

But when I tried to run it (latest version with PIP install), shows:

    Traceback (most recent call last):
      File "C:\My Documents\Scripts\Kin Qimen.py", line 1, in <module>
        from kinqimen import kinqimen
      File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 6, in <module>
        from config import *
    ModuleNotFoundError: No module named 'config'

I tried added lines but it doesn't help:

    import sys
    sys.path.append('C:\\Python38\\Lib\\site-packages\\kinqimen\\config.py')
    import config

I also tried (uninstalled the current version and install) older version:
    pip install kinqimen==0.0.2.7

But it still pops the same error, which I didn't encountered before.

Can you please have a look? Thank you!

**Comment by kentang2017** [comment]
fixed
