### ISSUE TITLE
0.0.6.0 seems missing 天盘寄宫。

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#31]
Dear Mr. Tang,

New version 0.0.6.0 seems missing the information of 天盘寄宫。

When using kinqimen-0.0.5.0 for (2022,3,28,12), it gives:
'天盤': [{'兌': '己', '乾': '丁', '坎': '乙', '艮': '壬', '震': '辛', '巽': '丙', '離': '癸', '坤': '戊'}, {'坎': '庚'}]

With kinqimen-0.0.6.0 for (2022,3,28,12), the second part {'坎': '庚'} is missing.
'天盤': {'兌': '己', '乾': '丁', '坎': '乙', '艮': '壬', '震': '辛', '巽': '丙', '離': '癸', '坤': '戊', '中': '庚'},

Can you please consider to add it back?

Thank you.

**Comment by kentang2017** [comment]
ok, will consider it

**Comment by P-Rainbow** [comment]
@kentang2017 , good day, Mr. Tang.

Can you please add on the 天盘寄宫 information in the current updates of Kinqimen?

Thank you.

**Comment by P-Rainbow** [comment]
Closing this Issue for in the new version of Kinqimen, it refers to '中'. (中宫)
