### ISSUE TITLE
fu_head, TypeError: 'NoneType' object is not subscriptable`

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#32]
Good morning Mr Tang,

Hope you are very well.

In using the kinqimen, I have below error popup.

Can you please have a look? Thank you.

    qimen = kinqimen.Qimen(2022,11,11,18).pan()

    # sxtwl 2.0.6
    # kinqimen 0.0.6.0

`Traceback (most recent call last):
  File "C:\My Documents\Scripts\Qimen 1.py", line 179, in <module>
    qimen = kinqimen.Qimen(2022,11,11,18).pan()
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 258, in pan
    return {"干支":self.gangzhi()[0]+"年"+self.gangzhi()[1]+"月"+self.gangzhi()[2]+"日"+self.gangzhi()[3]+"時","旬首":self.shun(self.gangzhi()[2]),"旬空":self.daykong_shikong(),"局日":self.qimen_ju_day(), "排局":self.qimen_ju_name(), "節氣":self.find_jieqi(), "值符值使":self.zhifu_n_zhishi(), "天乙":self.tianyi(), "天盤":self.pan_sky(), "地盤":self.pan_earth(), "門":self.pan_door(),"星":self.pan_star()[0], "神":self.pan_god(), "馬星": {"天馬": self.moonhorse(),"丁馬":self.dinhorse(), "驛馬":self.hourhorse()}, "長生運": self.gong_chengsun()}
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 156, in pan_sky
    fu_head = self.hourganghzi_zhifu()[2]
TypeError: 'NoneType' object is not subscriptable`

**Comment by kentang2017** [comment]
hi, fixed

**Comment by P-Rainbow** [comment]
Thank you, Mr. Tang! @kentang2017
