### ISSUE TITLE
(2021,12,30,18) - AttributeError: 'tuple' object has no attribute 'keys'`

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#33]
Good day Mr Tang,

In using the kinqimen, I have below error popup.

Can you please have a look? Thank you.

qimen = kinqimen.Qimen(2021,12,30,18).pan()

# sxtwl 2.0.6
# kinqimen 0.0.6.1

`Traceback (most recent call last):
  File "C:\My Documents\Scripts\Qimen 1.py", line 17, in <module>
    qimen = kinqimen.Qimen(2021,12,30,18).pan()
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 258, in pan
    return {"干支":self.gangzhi()[0]+"年"+self.gangzhi()[1]+"月"+self.gangzhi()[2]+"日"+self.gangzhi()[3]+"時","旬首":self.shun(self.gangzhi()[2]),"旬空":self.daykong_shikong(),"局日":self.qimen_ju_day(), "排局":self.qimen_ju_name(), "節氣":self.find_jieqi(), "值符值使":self.zhifu_n_zhishi(), "天乙":self.tianyi(), "天盤":self.pan_sky(), "地盤":self.pan_earth(), "門":self.pan_door(),"星":self.pan_star()[0], "神":self.pan_god(), "馬星": {"天馬": self.moonhorse(),"丁馬":self.dinhorse(), "驛馬":self.hourhorse()}, "長生運": self.gong_chengsun()}
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 252, in gong_chengsun
    sky_pan_new = dict(zip(sky_pan.keys(),[{list(sky_pan.values())[y]: [find_twelve_luck_new.get(i) for i in sky_pan.values()][y]} for y in range(0,8)]))
AttributeError: 'tuple' object has no attribute 'keys'`

**Comment by kentang2017** [comment]
thank you for reporting, fixed already.

**Comment by P-Rainbow** [comment]
Thank you, @kentang2017 !

When using 0.0.6.2 for (2021,11,8,18), it gives another error.

Can you please have a look too?

    qimen = kinqimen.Qimen(2021,11,8,18).pan()


`Traceback (most recent call last):
  File "C:\My Documents\Scripts\Qimen 1.py", line 17, in <module>
    qimen = kinqimen.Qimen(2021,11,8,18).pan()
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 258, in pan
    return {"干支":self.gangzhi()[0]+"年"+self.gangzhi()[1]+"月"+self.gangzhi()[2]+"日"+self.gangzhi()[3]+"時","旬首":self.shun(self.gangzhi()[2]),"旬空":self.daykong_shikong(),"局日":self.qimen_ju_day(), "排局":self.qimen_ju_name(), "節氣":self.find_jieqi(), "值符值使":self.zhifu_n_zhishi(), "天乙":self.tianyi(), "天盤":self.pan_sky(), "地盤":self.pan_earth(), "門":self.pan_door(),"星":self.pan_star()[0], "神":self.pan_god(), "馬星": {"天馬": self.moonhorse(),"丁馬":self.dinhorse(), "驛馬":self.hourhorse()}, "長生運": self.gong_chengsun()}
  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 251, in gong_chengsun
    sky_pan = self.pan_sky()[1]
KeyError: 1`

**Comment by kentang2017** [comment]
fixed and take a look

**Comment by P-Rainbow** [comment]
@kentang2017 thanks again. perfectly resolved! :)
