### ISSUE TITLE
'長生運': '天盤': None 

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#35]
Hello Mr. Tang,

Hope you're very well!

When using kinqimen 0.0.6.3, it gives some None for '長生運': '天盤'.

Can you please have a look? Thank you.

    qimen = kinqimen.Qimen(2022,6,30,9).pan()

    {'干支': '壬寅年丙午月甲寅日己巳時', '旬首': '癸', '旬空': {'日空': '子丑', '時空': '戌亥'}, '局日': '甲己日', '排局': '陰遁三局中元', '節氣': '夏至', '值符值使': {'值符星宮': ['沖', '坤'], '值使門宮': ['傷', '兌']}, '天乙': '芮', '天盤': {'坤': '戊', '離': '壬', '巽': '庚', '震': '丁', '艮': '癸', '坎': '己', '乾': '辛', '兌': '乙', '中': '丙'}, '地盤': {'震': '戊', '巽': '乙', '中': '丙', '乾': '丁', '兌': '癸', '艮': '壬', '離': '辛', '坎': '庚', '坤': '己'}, '門': {'兌': '傷', '坤': '生', '離': '休', '巽': '開', '震': '驚', '艮': '死', '坎': '景', '乾': '杜'}, '星': {'坤': '沖', '離': '任', '巽': '蓬', '震': '心', '艮': '柱', '坎': '禽', '乾': '英', '兌': '輔'}, '神': {'坤': '符', '離': '蛇', '巽': '陰', '震': '合', '艮': '虎', '坎': '玄', '乾': '地', '兌': '天'}, '馬星': {'天馬': '午', '丁馬': '巳', '驛馬': '亥'}, '長生運': {'天盤': {'坤': {'戊': None}, '離': {'壬': None}, '巽': {'庚': None}, '震': {'丁': None}, '艮': {'癸': None}, '坎': {'己': None}, '乾': {'辛': None}, '兌': {'乙': None}}, '地盤': {'震': {'戊': '養'}, '巽': {'乙': '帝旺'}, '中': {'丙': '病'}, '乾': {'丁': '死'}, '兌': {'癸': '沐浴'}, '艮': {'壬': '長生'}, '離': {'辛': '胎'}, '坎': {'庚': '絕'}, '坤': {'己': '墓'}}}}

**Comment by kentang2017** [comment]
fixed and please try 0.0.6.4

**Comment by P-Rainbow** [comment]
Perfect, Mr. Tang @kentang2017 !

Thank you for the upgrade!
