### ISSUE TITLE
日干 missing when 寄宫

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#4]
@kentang2017 So sorry to trouble you again for another question.

In case when the 日干 is 寄宫, it seems it is missing.

For example, 2021年3月9日9时, 日干 丙 falls in 巽宫. When the result is printed, 巽宫 is not showing the 日干 丙:

`干支 辛丑年辛卯月丙辰日癸巳時`
`天盤 {'震': '庚', '巽': '壬', '離': '戊', '坤': '乙', '兌': '辛', '乾': '己', '坎': '癸', '艮': '丁'}`

Can you please have a look? Thank you.

[2021年3月9日9时20分26秒](https://i.ibb.co/p4C6qY0/3-9-2021-4-21-30-PM.png)

**Comment by kentang2017** [comment]
it doesn't have such function yet.
![image](https://user-images.githubusercontent.com/34528743/110466119-46aaf180-8110-11eb-882c-5f058f7bf6de.png)

**Comment by P-Rainbow** [comment]
@kentang2017 thank you for the reply.

So in this case, it doesn't tell which 宫 the 日干 fall into...

As it's important information, would you consider to add on this info in future updates?

**Comment by kentang2017** [comment]
the ninth 干 on both 天盤 & 地盤 will be added soon.

**Comment by kentang2017** [comment]
done.
the ninth 干 on earth pan must be in the middle while the ninth 干 on sky pan must be in one of the eight doors where under 天芮/禽

**Comment by P-Rainbow** [comment]
@kentang2017 , thanks!

After pip install the latest version, the errors comes:
`ModuleNotFoundError: No module named 'config'`

Can you please have a look? Thank you.

**Comment by kentang2017** [comment]
Try update to 0.0.3.2

**Comment by P-Rainbow** [comment]
@kentang2017, Thank you for your efforts again!

I will test and use it!

**Comment by P-Rainbow** [comment]
@kentang2017, the update works very well!

Just another small thing - the sample given on the page [](https://github.com/kentang2017/kinqimen), the line doesn't work on my computer:
`from kinqimen import Qimen`

And I can use:
`from kinqimen import kinqimen`
'kinqimen.Qimen(2021,3,9,9).pan()'
