### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'minute'

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#40]
Good day, Mr. Tang:

How have you been? Hope you are very well!

Version 0.0.6.5 pops "TypeError: __init__() missing 1 required positional argument: 'minute'" from below line:

    qimen = kinqimen.Qimen(2022,6,30,9).pan()

Version 0.0.6.4 works totally fine. Can you please take a look? 

Thank you!

**Comment by kentang2017** [comment]
起盤需要年月日時分

**Comment by P-Rainbow** [comment]
Thank you, Mr. Tang!
