### ISSUE TITLE
Can you please update the use sample?

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#41]
Dear Mr. Tang,

Hope you're very well.

Can you please consider to update the use sample on pypi and github?

1. On https://pypi.org/project/kinqimen/, "3. 起課方式 Quickstart"

    from kinqimen import kinqimen
    kinqimen.Qimen(year, month, day, hour).pan()

When runs it with version 0.0.6.5. I have error:

    TypeError: __init__() missing 1 required positional argument: 'minute'.

2. On github, it gives "3. 起課方式 Quickstart"

    from kinqimen import kinqimen
    kinqimen.Qimen(year, month, day, hour).pan(1)     # 1:拆補 2:置閏

When runs it with version 0.0.6.5. I have error:

    TypeError: __init__() missing 1 required positional argument: 'minute'
    
When tried "kinqimen.Qimen(2021,12,13,19,15).pan(1)", I have error:

    TypeError: pan() takes 1 positional argument but 2 were given

When tried,

    qimen = kinqimen.Qimen(2023,12,13,19,26)
    print (qimen)

It gives "<kinqimen.kinqimen.Qimen object at 0x000001935072EC40>" only.

Thank you!

**Comment by kentang2017** [comment]
1. i havent uploaded the updated code on PYPI
2. if you use pip to install, just ignore the newest code or perhaps directly get the uptodate code on github

**Comment by P-Rainbow** [comment]
Thank you for your reply, Mr. Tang!

Your creation stands out as truly exceptional and widely relied upon. I encourage you to continue nurturing and enhancing it. This is a positive path towards personal growth, product excellence, and the advancement of knowledge. I have every confidence in your ability to excel and improve even further!
