### ISSUE TITLE
AttributeError: module 'config' has no attribute 'gangzhi'

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#42]
Hi Mr, Tang!

I downloaded the code from the github page, and tried it:

    kinqimen.Qimen(2022,12,13,19,26).pan(1)
    
    print (qimen)

It prints out:

    AttributeError: module 'config' has no attribute 'gangzhi'

Can you please enlighten me the right use? Thank you.

**Comment by kentang2017** [comment]
please download the whole project

**Comment by P-Rainbow** [comment]
@kentang2017 , thank you for your reply!

I did use "Download ZIP" from the green Code option, then unzip the content to my ......Python38\Lib\site-packages\kinqimen\.

It still shows the same error....

![image](https://github.com/kentang2017/kinqimen/assets/43132563/2bf042c5-db03-4d74-8c17-455d2cf1c0a9)

**Comment by kentang2017** [comment]
Did you uninstall the old one on your pc ,like pip uninstall kinqimen

**Comment by P-Rainbow** [comment]
@kentang2017, thank you for your reply.

I've used "pip uninstall kinqimen", and make sure my "......Python38\Lib\site-packages\" has no any sub-solders for kinqimen.

Then I download the whole project as kinqimen-master.zip. Then I create a sub-folder "kinqimen" in "......Python38\Lib\site-packages\". Unzip "kinqimen-master.zip"'s content to "......Python38\Lib\site-packages\kinqimen".

When used:

    qimen = kinqimen.Qimen(2021,12,13,18, 26).pan(1)

It still shows:

    File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\site-packages\kinqimen\kinqimen.py", line 291, in pan
    gz = config.gangzhi(self.year,
    AttributeError: module 'config' has no attribute 'gangzhi'

**Comment by kentang2017** [comment]
please follow the below steps:

1. download the entire folder "kinqimen" from Github
2. create a new .py file in the "kinqimen" folder , for example new.py
3. enter below code on new.py:
`    from kinqimen import Qimen
     print(Qimen(2024,5,13,11,32).pan(2))`
the code should be executed without problems

**Comment by P-Rainbow** [comment]
@kentang2017 thank you again for the reply, and step by step guide.

Yes, now it works!
