### ISSUE TITLE
置潤法與拆補法得到的奇門局一樣

### ISSUE THREAD

**Issue by jackygu2006** [kentang2017/kinqimen#43]
置潤法和拆補法在多數情況下是一致的，但在有些特殊日期不同，舉例：
2004年9月1日中午12點，通過拆補法應該使用處暑節氣上元，即隱遁一局，但使用置潤法應該使用白露節氣上元，即隱遁九局。
但是程序執行的結果卻是一樣。

我看了源碼，应该是在config.py的qimen_ju_name_zhirun方法最后，无论什么条件，都 return "{}{}局{}".format(find_yingyang, kooks, three_yuen)，导致。

**Comment by kentang2017** [comment]
知道錯在哪裡, 已修正。 line 371 if dgz_dist != "日干是符頭" and difference >= 9 and difference < 15: #超神  多或等於9天至少於15天
