### ISSUE TITLE
奇儀落宮的十二狀態

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#5]
@kentang2017 Mr. Tang, I am not sure if it's proper, but please just allow me to put it down (if not, please let me know and I will delete this Issue)

Many Qimen software does not show 奇儀落宮的十二狀態，即：長生、沐浴、冠帶..... 

Is it possible that you can consider to add in this information that KinQiMen can display them accordingly?

For example, 2021年 03 月 09日 09時，坎宮內有 癸 有 辛。辛在坎宮為 長生。癸在坎宮為 臨官，如此類推。

Thank you！

**Comment by kentang2017** [comment]
yes of course it is possible.

**Comment by P-Rainbow** [comment]
@kentang2017 , thank you for your attention willingness to improve it, Mr. Tang!

Unifying Yi science and data science, you are the only one!

**Comment by kentang2017** [comment]
長生十二神 is added.

**Comment by P-Rainbow** [comment]
@kentang2017 thank you for the hard work.

`from kinqimen import kinqimen`

`qimen = kinqimen.Qimen(2021,3,9,9).pan()`

`for k, v in qimen.items():`
`print (k, v)`

Output:
`干支 辛丑年辛卯月丙辰日癸巳時`
`旬首 癸`
`旬空 {'日空': '子丑', '時空': '午未'}`
`局日 丙辛日`
`排局 陽遁七局中元`
`節氣 驚蟄`
`值符值使 {'值符星宮': ['英', '震'], '值使門宮': ['景', '離']}`
`天乙 沖`
`天盤 ({'震': '庚', '巽': '壬', '離': '戊', '坤': '乙', '兌': '辛', '乾': '己', '坎': '癸', '艮': '丁'}, {'巽': '丙'})`
`地盤 {'兌': '戊', '艮': '己', '離': '庚', '坎': '辛', '坤': '壬', '震': '癸', '巽': '丁', '中': '丙', '乾': '乙'}`
`門 {'離': '景', '坤': '死', '兌': '驚', '乾': '開', '坎': '休', '艮': '生', '震': '傷', '巽': '杜'}`
`星 {'震': '英', '巽': '禽', '離': '柱', '坤': '心', '兌': '蓬', '乾': '任', '坎': '沖', '艮': '輔'}`
`神 {'震': '符', '巽': '蛇', '離': '陰', '坤': '合', '兌': '勾', '乾': '雀', '坎': '地', '艮': '天'}`
`馬星 {'天馬': '戌', '丁馬': '巳', '驛馬': '亥'}`
`長生十二神 {'寅': '長生', '卯': '沐浴', '辰': '冠帶', '巳': '臨冠', '午': '帝旺', '未': '衰', '申': '病', '酉': '死', '戌': '墓', '亥': '絕', '子': '胎', '丑': '養'}`

Instead of having:
`長生十二神 {'寅': '長生', '卯': '沐浴', '辰': '冠帶', '巳': '臨冠', '午': '帝旺', '未': '衰', '申': '病', '酉': '死', '戌': '墓', '亥': '絕', '子': '胎', '丑': '養'}`

**Would it be possible to have:**
`坎 {'辛' : '長生', '癸' : '臨官'}`
`艮 {'丁' : ‘死 墓', ’己' : '死 墓'}`
`震 {'庚' : ‘胎', ’癸' : '長生'}`
...
...

**Comment by kentang2017** [comment]
Yeah it is possible. give me some time.

**Comment by kentang2017** [comment]
done

**Comment by P-Rainbow** [comment]
@kentang2017 good morning Mr. Tang, I am amazed by your professionalism, efficiency and skills!

KinQimen is now the world best Python Qimen library!

Great work!

**Comment by kentang2017** [comment]
thank you for advice and that helps improvement
