### ISSUE TITLE
list consistency ?

### ISSUE THREAD

**Issue by i-arun-samui** [kentang2017/kinqimen#7]
Hi,

Thanks for library, I'm wondering if those lists are correct - 10 items and one duplicate value:

newgtw_order = re.findall("..","地籥天關唐符風雲唐符風雲雷公風伯天曹五符")
唐符 is duplicate

which is inconsistent with this one  - 12 items no duplicate values
gtw = re.findall("..","地籥六賊五符天曹地符風伯雷公雨師風雲唐符國印天關")

looking forward reading from you.

**Comment by kentang2017** [comment]
> Hi,
> 
> Thanks for library, I'm wondering if those lists are correct - 10 items and one duplicate value:
> 
> newgtw_order = re.findall("..","地籥天關唐符風雲唐符風雲雷公風伯天曹五符")
> 唐符 is duplicate
> 
> which is inconsistent with this one - 12 items no duplicate values
> gtw = re.findall("..","地籥六賊五符天曹地符風伯雷公雨師風雲唐符國印天關")
> 
> looking forward reading from you.

1. newgtw_order is a list which represents 子時s of those sixty jiazi days according to 重刻校增武侯八門神書 written by 胡獻忠。

**Comment by i-arun-samui** [comment]
thank you for explaining.

Best regards
