### ISSUE TITLE
0.0.4.0, ValueError: None is not in list

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#8]
Dear Mr. Tang,

When installed the 0.0.4.0 version, it gives error for some days. 

For example, no problem for 15th April 2021, but error pops if the date is 16th April onward. It's back to ok until 06th May 2021.

Can you please have a look? Thank you.

`Traceback (most recent call last):`

`  File "C:\My Documents\Scripts\Qimen.py", line 4, in <module>`

`    qimen = kinqimen.Qimen(2021, 4, 16, 9).pan()`

`  File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 18, in __init__`

`    self.g = self.gpan()`
 
` File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 224, in gpan`
 
`   c_gong = new_list(eight_gua, gong)`
 
` File "C:\Python38\lib\site-packages\kinqimen\config.py", line 26, in new_list`
 
`   zhihead_code = olist.index(o)`

`ValueError: None is not in list`

**Comment by kentang2017** [comment]
fixed, the problem comes from incompleted 旬首 list, please do pip install update

**Comment by P-Rainbow** [comment]
Brilliant! @kentang2017, thank you and wish you a good weekend!

**Comment by kentang2017** [comment]
> Brilliant! @kentang2017, thank you and wish you a good weekend!

you too!
