### ISSUE TITLE
05 May 14:00 is 壬辰月 instead of 癸巳月

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#9]
Hi Mr. Tang, hope you are very well.

Today when I am using kinqimen (time 2021 May 05, 14:00, it gives me:
`干支 辛丑年癸巳月癸丑日己未時`

But seems the time is:
`辛丑年　壬辰月　癸丑日　己未时　`

Can you please have a look?

Thank you.

**Comment by kentang2017** [comment]
癸巳月沒錯呀

**Comment by P-Rainbow** [comment]
嗯！有啲排盘显示 壬辰月。

![image](https://user-images.githubusercontent.com/43132563/117121246-eca07280-adc6-11eb-88ce-4a755bc16454.png)
